# Generated by Django 3.1.2 on 2020-10-17 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('timing', models.DateTimeField(default=datetime.datetime(2020, 10, 17, 17, 51, 20, 39085))),
            ],
        ),
    ]
