# Generated by Django 3.1.2 on 2020-10-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201018_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 14, 46, 36, 578433)),
        ),
    ]
