# Generated by Django 3.1.2 on 2020-10-17 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='%d%m%y')),
                ('description', models.TextField(max_length=250)),
                ('link', models.URLField(blank=True, default='#')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 17, 15, 59, 47, 22296))),
            ],
        ),
    ]
