# Generated by Django 3.1.2 on 2020-10-17 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 16, 54, 45, 607770)),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
