# Generated by Django 3.1.2 on 2020-10-17 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201017_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 17, 12, 45, 810357)),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
