# Generated by Django 3.1.2 on 2020-10-18 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201017_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 14, 21, 59, 195084)),
        ),
    ]
